spring:
  datasource:
    url: jdbc:h2:mem:movie_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: "" # Explicitly marking the password as empty for clarity
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        data:
    mongodb:
      uri: mongodb+srv://sujatha55:UJmTGm8SS5hiQvpj@cluster0.5reob.mongodb.net/movies?retryWrites=true&w=majority

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


server:
  servlet:
    context-path: /api
    port: 8080

logging:
  level:
    root: DEBUG
    org.springframework:
      security: DEBUG
      oauth2: DEBUG # Covers all oauth2-related logs
      web: DEBUG
    com.example.demo: DEBUG # Custom package-level logging
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG